### ISSUE TITLE
Map Modul - missing div with position relative

### ISSUE THREAD

**Issue by merlinmc** [itsam/imc#11]
Hi, it seems that the map module is missing an wrapping div with a heigt value. 
I added a wrapping <div id="imc_wrapper"> over <div id="imc-mod-map-canvas"></div> in the default.php and gave them the css properties and it works. 

Wrapping div in default.php

<div id="imc_wrapper">
<div id="imc-mod-map-canvas"></div>
</div>

css Value: 
 #imc_wrapper {height: 400px; position: relative; }

before:

![vorher](https://cloud.githubusercontent.com/assets/10464116/6468110/2daaae8a-c1d3-11e4-982e-c1956ce6ce76.jpg)

The Filter Module ist behind the map!

after:
![after](https://cloud.githubusercontent.com/assets/10464116/6468118/343d2534-c1d3-11e4-97f8-f6eaa71fcfb4.jpg)

**Comment by merlinmc** [comment]
The link to the webseite: 
http://www.ff-leopoldsdorf.net/index.php?option=com_imc&view=issues&Itemid=1742

**Comment by merlinmc** [comment]
After  an update  in the morning  it works  without  the modification.

**Comment by merlinmc** [comment]
Hi itsam!
I think we need it yet. A abolute div need a wrapping relative div ro work correctly.

kind regards
Christopher

**Comment by itsam** [comment]
Indeed. Although the problem is not a missing wrapper but the map module css itself... (should add mod class suffix
