### ISSUE TITLE
Feature Request for Modules

### ISSUE THREAD

**Issue by TGoodrich** [itsam/imc#12]
Could it be possible to add a Module Class Suffix, Caching and Cache Time for IMC Modules? Alot of the modules I use have these options but IMC3 does not. The Module Class Suffix would be very helpful as it would help style the modules.

**Comment by itsam** [comment]
Yes, these params should definitely be added. I mark this as "todo confirmed".
Also, please note that currently you need to set your cache at Joomla general configuration to
`ON - conservative caching`
