### ISSUE TITLE
not allowed to add a new comment

### ISSUE THREAD

**Issue by asehir** [itsam/imc#18]
How can I change permissions.

I checked imc permissions but there is nothing about comments.

Thanks

**Comment by asehir** [comment]
Also I can not see votes. There is nothing at general settings like the ex version.

How can I set comments and votes.

**Comment by itsam** [comment]
Comments are not yet implemented, the msg is misleading

**Comment by asehir** [comment]
So how can I remove "add comment" button.

**Comment by itsam** [comment]
You can temporary comment out lines 186-190 at [default.php](https://github.com/itsam/imc/blob/master/site/views/issue/tmpl/default.php)

**Comment by asehir** [comment]
Ok that works. Thanks a lot.
