### ISSUE TITLE
Fatal error: Class 'ImcHelper' not found in

### ISSUE THREAD

**Issue by asehir** [itsam/imc#20]
"Fatal error: Class 'ImcHelper' not found in ..... administrator/components/com_imc/models/log.php on line 62" I got this error when I try to update logs.

http://demo.asehir.net/

**Comment by asehir** [comment]
No solutions?

**Comment by itsam** [comment]
What do you mean? Issue fixed https://github.com/itsam/imc/commit/cd79eea486e029ec7802158ed800c59dd34fecfa

**Comment by asehir** [comment]
Ok I just saw it now.

Thanks.
