### ISSUE TITLE
user notifications

### ISSUE THREAD

**Issue by asehir** [itsam/imc#21]
User notifications are not working. I think notification settings on categories are only for administrator and is there any settings for user notifications?

http://demo.asehir.net/tr/

Thanks.

**Comment by itsam** [comment]
Have you check the settings at "Improve My City Mail Notifier" plugin?

**Comment by asehir** [comment]
Yes.

On change status to user --> Yes.

I tried about 10 times with different issues. and mail comes only once.?

Am I doing something wrong. Administrator notifications work fine.

**Comment by itsam** [comment]
@asehir Why issue is closed? Have you found a solution? Please give a brief explanation

**Comment by asehir** [comment]
Hi.

I just deleted all statues and created again. And It's working fine now. I don't know what was wrong. I did not change anything.

Thanks a lot.

**Comment by asehir** [comment]
Actually it send emails only if I creact issue as super user. and when I creat an issue with a registered account then notifications are not working.

**Comment by superdiogene** [comment]
Sehir Hello, sorry to bother you, could you kindly tell me what kind of apikey you used, I always receive an error message that informs me that the apikey is invalid. I'm going crazy, then I can not understand how you get the start page as your own or as an example of the site producer.

**Comment by asehir** [comment]
I dont have any apikey and I didnt get any error like that. What do you mean with start page? You must choose "imc issues" as main menu.

**Comment by superdiogene** [comment]
Asehir Thanks for the answer. I unfortunately have this message that appears Module IMC Map :: Google Maps API KEY missing. Then I would ask you how you place the map on the right as in your web Pagia single issue.
Here's an example of the page that I'm building: http://bustoarsizioedintorni.it/index.php/segnalazioni/issue/2
Thank you

**Comment by asehir** [comment]
I understand now. Go to;

Improve my city --> options --> Google map

You will see Google Maps API KEY field there. You need to get an api key from google developers and copy it there.

Thanks.

**Comment by superdiogene** [comment]
If I enter the API key map you will automatically appear on the right?

**Comment by asehir** [comment]
If you enter the key that error will disappear. and map will just work fine.

**Comment by superdiogene** [comment]
entered the code API key, but do not I see the map. Is there not something to be set?
If you do noise please let me know. Thank you

**Comment by itsam** [comment]
API KEY deals with Google API calls, NOT with the position of the map. Map is just a module and you can place it wherever you want according to your template
