### ISSUE TITLE
onClicking any button under improvemycity component.

### ISSUE THREAD

**Issue by zapresko** [itsam/imc#29]
Notice: Use of undefined constant DS - assumed 'DS' in C:\xampp\htdocs\joomla30\administrator\components\com_improvemycity\improvemycity.php on line 20

Notice: Use of undefined constant DS - assumed 'DS' in C:\xampp\htdocs\joomla30\administrator\components\com_improvemycity\improvemycity.php on line 20

Fatal error: Call to undefined method JController::getInstance() in C:\xampp\htdocs\joomla30\administrator\components\com_improvemycity\improvemycity.php on line 25

**Comment by itsam** [comment]
This component is for Joomla 3.X

**Comment by zapresko** [comment]
Thank you for the help,
