### ISSUE TITLE
IMC Stats Module or component option

### ISSUE THREAD

**Issue by krogias** [itsam/imc#30]
It could be a good and helpful idea to have a module (or an option) to show statistics about the issues (by category or/and by status).

**Comment by itsam** [comment]
There is. Take a look at http://www.improve-my-city.com/livedemo/analyze/

**Comment by krogias** [comment]
!? And how do we enable it!?

**Comment by itsam** [comment]
http://www.improve-my-city.com/pricing/
Although we are planning to open source a small portion of analytics/reports. Can't tell exact timeline
