### ISSUE TITLE
 --- normaly by now, I would be asking for help about the mobile app. how to get it working and stuff.

### ISSUE THREAD

**Issue by klleww** [itsam/imc#31]
im a student from a state university in the Philippines. Mindanao State University. www.msugensan.edu.ph (the site goes down every weekend cuz our web admin is a lazy old guy.)
18yrs graduating student. BS-IT

ive been looking around the internet for information technology projects that I can deploy in my local community and Ive been delving into IMC the past few months. I was thinking of deploying it as a small project here in my community.

What ive currently done:

>set up my own webserver ( http://improvemsugensan.ga ) - managed to get it working.. somehow..

>next thing i want to do is deploy the mobile app. (ive been trying to do it for the past few days but i cant get the mobile app to work for my server. -joomla 2.5 and joomla 3 compatibility issues i guess?)  
       
 --- normaly by now, I would be asking for help about the mobile app. how to get it working and stuff.
 
 --- im going to ask for a different kind of help.
        
           I would like to deploy IMC on my local community that covers my school and the community around it. Brgy. Uhaw. 

     -my plan to market is by tapping on the student government and the local government. 
        we start simple. think of this as a <bold>START-UP PARTNERSHIP</bold>

         once I have a fully capable mobile app that can be used for my current webserver I will deploy it
         here.
         now my work here is to filter small scale incoming issues that can we can handle, meaning, " low
         cost issues "
  
            receive issue -> filter issue -> if small scale -> tap on student government and local government  -> act on issue

        the way I see it, if it runs well, we could have a shot at partnering up with the local government and I do believe ill have the chance of selling your product to them. ill be like your sales person. I wont be handling any money. no money goes thru me. it'll be IMC - Local government that will have a contract. 

        I am currently connected with the local government because we are making a system for them right now. Its only a matter of introducing the idea to them, they are open to try new information systems. 

   thats all i ask. a chance.

   too lazy to write an email so ill just comment it here. 

   really hoping to hear from you guys. Improve My City is really a great app.

**Comment by itsam** [comment]
Please contact at www.improve-my-city.com
