### ISSUE TITLE
Something wrong Google Maps correctly

### ISSUE THREAD

**Issue by lungkao** [itsam/imc#34]
Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

**Comment by itsam** [comment]
Please give more details. What does the console says?

**Comment by lungkao** [comment]
i use on joomla 3.5.1 
![screen shot 2559-05-21 at 11 46 13 am](https://cloud.githubusercontent.com/assets/2047778/15446387/d45563f4-1f49-11e6-92c1-51aee5964593.png)

[systeminfo-2016-05-21T04-48-26+00-00.txt](https://github.com/itsam/imc/files/275707/systeminfo-2016-05-21T04-48-26.00-00.txt)

**Comment by krogias** [comment]
Are you in localhost or in live site?

**Comment by itsam** [comment]
Google changed their policy. You have to provide a valid key for your domain.

**Comment by itsam** [comment]
Shall we close this? Someone please confirm the solution

**Comment by itsam** [comment]
See also #49 and to be future proof, include static maps to your key. Will be needed for the print-issue feature

**Comment by krogias** [comment]
I get this error only on my localhost, with no API. Live site with API works fine.

**Comment by itsam** [comment]
Have no issue either in localhost or live

**Comment by krogias** [comment]
Google Maps API error: RefererNotAllowedMapError https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: https://www.localhost/imc_.kb @ js?key=**********&language=el&libraries=geometry:34
