### ISSUE TITLE
ReferenceError: MarkerClusterer is not defined

### ISSUE THREAD

**Issue by krogias** [itsam/imc#35]
Something must have been changed by Google Maps, because the "Clustering markers" option doesn't work any more.
I get error: 
> ReferenceError: MarkerClusterer is not defined
> setMarkers/json</<.success()
> m.Callbacks/j()
> m.Callbacks/k.fireWith()
> x()
> .send/b()

**Comment by itsam** [comment]
Fixed. Problem caused due to Google moved to Github

**Comment by krogias** [comment]
Same issue again.
