### ISSUE TITLE
Back End Problem

### ISSUE THREAD

**Issue by TGoodrich** [itsam/imc#4]
So happy for IMC3 release! I am currently testing this on a staging site and have run into a snag.
I tried to add my Google Maps API key in the IMC options but found the "SAVE", "SAVE & CLOSE" and "CANCEL" buttons do not work so I can not save my key.

**Comment by itsam** [comment]
Cannot duplicate the issue. What do you mean "do not work"? You can press the button and receive and error or you cannot press the button at all (like an invisible div is on top)?

**Comment by TGoodrich** [comment]
When clicking the above mentioned buttons nothing happens. If it helps I am using Joomla  3.4.0 and ISIS administrator template. I am not seeing this issue with the other components I have installed.

Please let me know if there is any other information I can give to help diagnose the problem.

**Comment by itsam** [comment]
Your Joomla 3.4.0 is a clean installation or an update?

**Comment by TGoodrich** [comment]
My Joomla 3.4.0 is an update from 3.3.6

I'm not sure if this information is helpful or not but I am seeing these errors in Chrome Dev Tools:
Uncaught SyntaxError: Unexpected token ;   in   index.php?option=com_config&view=component&component=com_imc:240

Uncaught ReferenceError: itemId is not defined   in   gmap.js:50 
(anonymous function)   in   gmap.js:50 
m.Callbacks.j   in   jquery.min.js:2
m.Callbacks.k.fireWith   in   jquery.min.js:2
m.extend.ready   in   jquery.min.js:2
J   in   jquery.min.js:2

Clicking for example the "SAVE" button this error pops up in DEV Tools:
Uncaught TypeError: Cannot read property 'task' of null   in   core.js:1
Joomla.submitform   in   core.js:1
Joomla.submitbutton   in   core.js:1
onclick   in   index.php?option=com_config&view=component&component=com_imc:633 

The above errors do not happen in other component options.

**Comment by gpalmas** [comment]
It's the same for me.
My Firebug output is:

TypeError: form is null
http://www.mycityup.com/TEST/media/system/js/core.js
Line 1

I'm running it in a test environment with the latest J3 version.

**Comment by itsam** [comment]
Just updated the repo. Can someone plz verify if problem solved?

**Comment by TGoodrich** [comment]
I have updated IMC in my Joomla install and can verify the problem is fixed for me. As a side note I can now also see the google map in options.

**Comment by gpalmas** [comment]
Ok for me. Now I can make some tests on the frontend... ;-)

**Comment by itsam** [comment]
@TGoodrich, @gpalmas thank you for your contribution. I close the issue as bug is fixed
