### ISSUE TITLE
Find My position is not working.

### ISSUE THREAD

**Issue by asehir** [itsam/imc#40]
Find My position is not working. and I got following error;

Error: The Geolocation service failed.

I got Google Maps API KEY and everything is working fine except "Find My position"

Thanks.

**Comment by asehir** [comment]
I think it works only with SSL.

**Comment by itsam** [comment]
This feature should be allowed by your browser (usually a popup appears first)

**Comment by asehir** [comment]
No that only works with web sites with ssl anymore. It works with firefox but Chrome only works if website has ssl.

Thanks for reply.
