### ISSUE TITLE
"Clustering markers" option problem

### ISSUE THREAD

**Issue by krogias** [itsam/imc#43]
"Clustering markers" option doesn't work again after the last Joomla! 3.6.0 update

**Comment by krogias** [comment]
Path to google markerclusterer.js changed again: 
https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/src/markerclusterer.js

**Comment by itsam** [comment]
Seems to be :lock: now

**Comment by krogias** [comment]
yup. Sorry for that. It was issue form the google maps end.
