### ISSUE TITLE
Problem with images with Greek Characters

### ISSUE THREAD

**Issue by krogias** [itsam/imc#56]
Although image files with greek characters are uploaded fine, you cannot see them, unless you rename them using Latin characters.

**Comment by itsam** [comment]
Your server runs on Window or Linux?

**Comment by krogias** [comment]
Windows

**Comment by itsam** [comment]
Use Linux to keep your mind free :smiley: (no really, Windows and production server are not a good match)
Nevertheless, the issue in Windows is tricky. A method to transliterate the name should be introduced but we are not going to support that at this time. Your contributions are always welcome

**Comment by krogias** [comment]
Wish I could use linux... :)
