### ISSUE TITLE
JS conflict in Joomla 3.7.1 

### ISSUE THREAD

**Issue by krogias** [itsam/imc#66]
/plugins/system/t3/base-bs3/bootstrap/js/bootstrap.js has to be excluded from js compression in JA Purity III, otherwise map module does not show up.
JA PURITY iii 1.2.0
T3 Framework 2.6.4

**Comment by alenkovich** [comment]
Hi!
How do you exclude bootstrap.js? And is there a more convenient way of handling this conflict?

I'm on Joomla 3.8.3

Best,
Alen

**Comment by itsam** [comment]
Closed due to inactivity
