### ISSUE TITLE
Layout Question

### ISSUE THREAD

**Issue by TGoodrich** [itsam/imc#7]
Should the new IMC3 layout appear similar to this demo?
http://smartcitydemos.urenio.org/index.php

My instal looks unfinished with missing options and features. I ask because its possible the problem may be due to the template I am using.

Also, is there a demo for the IMC3 to compare to?

Thx

**Comment by itsam** [comment]
The official demo will be published at http://www.improve-my-city.com/imc3 but temporarily you can check at http://mklab.iti.gr/joomla3.
Please note that currently the component is fully workable on bootstrap based themes

**Comment by TGoodrich** [comment]
WOW the demo looks great! Thank you for posting the link.

My IMC3 appears completely different though. After comparing my IMC instal to your demo it looks like maybe some of the css is missing. I did a side by side comparison using Chrome Dev Tools.

**Comment by itsam** [comment]
There is certainly a known "problem" with custom CSS which regularly shouldn't be part of the component (will be removed) at https://github.com/itsam/imc/blob/master/modules/mod_imcmap/assets/css/style.css
Also, for the demo I have overrided purity iii (which of course has nothing to do with IMC3)

**Comment by itsam** [comment]
Also lines 50-62 at https://github.com/itsam/imc/blob/master/modules/mod_imcmap/mod_imcmap.php shouldn't be part of the component and will be moved to component settings. This way we can achieve advanced layouts...

**Comment by itsam** [comment]
Demo can be found at: www.improve-my-city.com/demo3
