### ISSUE TITLE
Cannot unpublish or delete issues (joomla! 3.9.1)

### ISSUE THREAD

**Issue by krogias** [itsam/imc#74]
When in backend as super user, cannot "publish" or "delete" an issue. (Joomla 3.9.1)

**Comment by itsam** [comment]
Have to check what has changed from 3.9.0 (works) to 3.9.1

**Comment by itsam** [comment]
For a reason JHTML::_ does not use the correct method causing the following

`window.listItemTask() is deprecated use Joomla.listItemTask() instead window.listItemTask`

and

`window.submitform() is deprecated use Joomla.submitform() instead`

**Comment by krogias** [comment]
It started to become a big problem because we have a lot of double issues that need to be deleted.

**Comment by itsam** [comment]
Joomla 3.9.2 solves the bug
