### ISSUE TITLE
Error upload photos 

### ISSUE THREAD

**Issue by kaiser36** [itsam/imc#75]
Hi I have a problem when i try to upload a photo to a new issue gives a error 
SyntaxError: Unexpected token < in JSON at position 0

it uploads up to 100% but then it gives this error.
I disable cache already 
Does anyone know how to solve???

**Comment by itsam** [comment]
Hi,
I cannot reproduce the error, could you please send some further details such as Joomla version? Uploading from the frontend or the administrator side?

**Comment by kaiser36** [comment]
Hi i resolved because i change de php version to 7.0
