### ISSUE TITLE
Error 1064

### ISSUE THREAD

**Issue by kaiser36** [itsam/imc#77]
Hi 

I have this error "1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND a.state = 1 ORDER BY a.created' at line 6 "whenever I click on the link of the issue that is sent by email.

The issue link is
https://portalmaiscidadao.pt/index.php/en/ocorrencia/issue/8.html

And the email link is different
https://portalmaiscidadao.pt/index.php/en/participar-ocorrencia/issue/8.html

How do I change the issue link so I do not give the error?
Can you help please?

**Comment by itsam** [comment]
On Plugins: Improve My City Mail Notifier --> Tab: Mail notifications
you set "Your public domain" and "Menu alias to IMC"

**Comment by kaiser36** [comment]
Hi 

I put in Your public domain: https://portalmaiscidadao.pt and Menu alias to IMC: ocorrencia and now i dont recived email with the link 

Can you help please?

**Comment by kaiser36** [comment]
Its ok now  thanks for your help

**Comment by kaiser36** [comment]
Hi there, im again with the error on the link i have the alias like this 

to report a new issue the menu alias is "ocorrencia" and the link is https://portalmaiscidadao.pt/index.php/pt/ocorrencia.html

to see the list of issues the alias is "reportar-ocorrencia" and the link is 
https://portalmaiscidadao.pt/index.php/pt/reportar-ocorrencia.html

In the plugin Improve My City Mail Notifier - Menu alias to IMC i have "reportar-ocorrencia" but when send the email with link send with the link wrong portalmaiscidadao.pt/index.php/pt/ocorrencia/issue/35.html

I want to send with this link 
portalmaiscidadao.pt/index.php/pt/reportar-ocorrencia/issue/35.html

Can you help please?
tks
