### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by gpalmas** [itsam/imc#8]
With the template which I am using there seem to be problems with layout.
You can take a look here: http://www.mycityup.com/TEST/mycityreports
I guess it's hard to develope the component to be properly displayed with different templates. I suggest you do it for the most common framework: T3, Warp and Gantry.
Now I am using Gantry. As soon as I can will prepare you a test environment so you can use it for testing purposes!

**Comment by itsam** [comment]
The goal is either to include a custom CSS grid and modal functionality (which is actually already there in the filters module and should probably be part of the core component) or create different layouts for each of the common frameworks (T3, Warp, Gantry). 

I think it is wiser to go with the more generic former solution and include own CSS rules at least for the layout.

Nevertheless a testing environment is more than welcome :)

**Comment by gpalmas** [comment]
Yes, it's logic.
This is a copy of my fully updated test environment, available for you, with a Gantry based template already active.

Frontend: http://www.mycityup.com/TEST3/
Backend: http://www.mycityup.com/TEST3/administrator
User: admin
Password: adminpwd

You can use it and edit all you want. I'm working on another environment to make my tests.
I hope it can be useful...

**Comment by itsam** [comment]
Thanks @gpalmas :+1:
