### ISSUE TITLE
Template - Map Problem - and some other questions

### ISSUE THREAD

**Issue by merlinmc** [itsam/imc#9]
Hi i installed IMC on Joomla 3.4 and at the moment i use the purity III Template. But therer are some troubles. 
- The Map didn't show an a single issue.
- How can i activate that i can wirte a comment - it says to me comments not allowed
- Vote ist already possible?
- How can i change the markers icon?

Link to the webseite: http://www.ff-leopoldsdorf.net/index.php?option=com_imc&view=issues&Itemid=1742

thanky forward Cristopher

**Comment by itsam** [comment]
- Have you set an API key in administrator options?
- To be included very soon
- Vote is fully supported but is available only for registered users
- Marker icons are set in each category (tab Options -> Image)

**Comment by merlinmc** [comment]
Since  the  update  in the morning the map  on  a Single issue  works well .

**Comment by merlinmc** [comment]
Markers  work  well!

**Comment by itsam** [comment]
Nice, should we close this issue?
